// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerAchievementsBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerAchievementsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SayHello(string name)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "PlayerAchievements",
                "SayHello",
                new Dictionary<string, object>()
                {
                    {"name", name},
                });
        }

        public async Task<string> GetAchievementsByCategory(string category, string saveData)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "PlayerAchievements",
                "GetAchievementsByCategory",
                new Dictionary<string, object>()
                {
                    {"category", category},
                    {"saveData", saveData},
                });
        }
    }
}
