//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/BattlefieldHotkeys.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BattlefieldHotkeys: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BattlefieldHotkeys()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BattlefieldHotkeys"",
    ""maps"": [
        {
            ""name"": ""Shortcuts"",
            ""id"": ""cfd5d95c-72f0-486b-a466-b05afea7b210"",
            ""actions"": [
                {
                    ""name"": ""PlayHandCards"",
                    ""type"": ""Button"",
                    ""id"": ""6fc4e6f4-2006-49a4-a80e-e653bb36b7c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RestartGame"",
                    ""type"": ""Button"",
                    ""id"": ""848c4cf8-bf24-4c5f-9882-88a6263c14d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SurrenderGame"",
                    ""type"": ""Button"",
                    ""id"": ""db3ba314-b505-4925-a895-aa17889c2fe6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""06f63ab2-2deb-49fc-ae62-77bfd433c267"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48aa44ac-51b5-40f1-9638-f42948e04477"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RestartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1c445d6-cb43-4abf-8cc5-ff51785a98cd"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SurrenderGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67ee8219-1b7c-406c-89b2-628d196ea4b7"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""378a8de5-81e6-4557-9826-1197938d159d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f1a6066-c059-4592-a6e5-c8bf9d56184b"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b0b0636-2a16-470e-9352-dd0985bfce98"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eec2d58b-aae0-4e92-bf9f-3f9a7275ac17"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4aef0152-e538-40d9-803a-03bf525e8ac6"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77706a8c-155f-4725-9107-dbcbacacb5a9"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayHandCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DashboardShortcuts"",
            ""id"": ""3f53b2d2-bce1-4853-801e-4fa93f11864b"",
            ""actions"": [
                {
                    ""name"": ""StartDuel"",
                    ""type"": ""Button"",
                    ""id"": ""21ceeda9-3c89-4878-9f2a-9a9d184e8788"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartPvP"",
                    ""type"": ""Button"",
                    ""id"": ""94322bd9-f05f-4675-b669-33b530755271"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e2786d56-af47-4eab-af08-d1abb8119220"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartDuel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b68bd9e2-542a-4356-95f4-9095bcde281f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartDuel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a38b157f-b0d9-476b-9cf1-845f8ee7291a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartDuel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91cac276-8e04-4b6c-a584-33d40f21a96c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartDuel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d6da594-3ba8-4719-a4cd-f483c7af4e5b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartDuel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""456ef855-294c-4af0-a74c-b55c5d6248fc"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartDuel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12bd8c23-2bda-402d-b332-646b1eaaa867"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartDuel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26f5df22-a7cd-470b-9c02-55a73227cc4c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""DashboardShortcuts"",
                    ""action"": ""StartPvP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""BattlefieldHotkeys"",
            ""bindingGroup"": ""BattlefieldHotkeys"",
            ""devices"": []
        },
        {
            ""name"": ""DashboardShortcuts"",
            ""bindingGroup"": ""DashboardShortcuts"",
            ""devices"": []
        }
    ]
}");
        // Shortcuts
        m_Shortcuts = asset.FindActionMap("Shortcuts", throwIfNotFound: true);
        m_Shortcuts_PlayHandCards = m_Shortcuts.FindAction("PlayHandCards", throwIfNotFound: true);
        m_Shortcuts_RestartGame = m_Shortcuts.FindAction("RestartGame", throwIfNotFound: true);
        m_Shortcuts_SurrenderGame = m_Shortcuts.FindAction("SurrenderGame", throwIfNotFound: true);
        // DashboardShortcuts
        m_DashboardShortcuts = asset.FindActionMap("DashboardShortcuts", throwIfNotFound: true);
        m_DashboardShortcuts_StartDuel = m_DashboardShortcuts.FindAction("StartDuel", throwIfNotFound: true);
        m_DashboardShortcuts_StartPvP = m_DashboardShortcuts.FindAction("StartPvP", throwIfNotFound: true);
    }

    ~@BattlefieldHotkeys()
    {
        UnityEngine.Debug.Assert(!m_Shortcuts.enabled, "This will cause a leak and performance issues, BattlefieldHotkeys.Shortcuts.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_DashboardShortcuts.enabled, "This will cause a leak and performance issues, BattlefieldHotkeys.DashboardShortcuts.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Shortcuts
    private readonly InputActionMap m_Shortcuts;
    private List<IShortcutsActions> m_ShortcutsActionsCallbackInterfaces = new List<IShortcutsActions>();
    private readonly InputAction m_Shortcuts_PlayHandCards;
    private readonly InputAction m_Shortcuts_RestartGame;
    private readonly InputAction m_Shortcuts_SurrenderGame;
    public struct ShortcutsActions
    {
        private @BattlefieldHotkeys m_Wrapper;
        public ShortcutsActions(@BattlefieldHotkeys wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayHandCards => m_Wrapper.m_Shortcuts_PlayHandCards;
        public InputAction @RestartGame => m_Wrapper.m_Shortcuts_RestartGame;
        public InputAction @SurrenderGame => m_Wrapper.m_Shortcuts_SurrenderGame;
        public InputActionMap Get() { return m_Wrapper.m_Shortcuts; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShortcutsActions set) { return set.Get(); }
        public void AddCallbacks(IShortcutsActions instance)
        {
            if (instance == null || m_Wrapper.m_ShortcutsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShortcutsActionsCallbackInterfaces.Add(instance);
            @PlayHandCards.started += instance.OnPlayHandCards;
            @PlayHandCards.performed += instance.OnPlayHandCards;
            @PlayHandCards.canceled += instance.OnPlayHandCards;
            @RestartGame.started += instance.OnRestartGame;
            @RestartGame.performed += instance.OnRestartGame;
            @RestartGame.canceled += instance.OnRestartGame;
            @SurrenderGame.started += instance.OnSurrenderGame;
            @SurrenderGame.performed += instance.OnSurrenderGame;
            @SurrenderGame.canceled += instance.OnSurrenderGame;
        }

        private void UnregisterCallbacks(IShortcutsActions instance)
        {
            @PlayHandCards.started -= instance.OnPlayHandCards;
            @PlayHandCards.performed -= instance.OnPlayHandCards;
            @PlayHandCards.canceled -= instance.OnPlayHandCards;
            @RestartGame.started -= instance.OnRestartGame;
            @RestartGame.performed -= instance.OnRestartGame;
            @RestartGame.canceled -= instance.OnRestartGame;
            @SurrenderGame.started -= instance.OnSurrenderGame;
            @SurrenderGame.performed -= instance.OnSurrenderGame;
            @SurrenderGame.canceled -= instance.OnSurrenderGame;
        }

        public void RemoveCallbacks(IShortcutsActions instance)
        {
            if (m_Wrapper.m_ShortcutsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShortcutsActions instance)
        {
            foreach (var item in m_Wrapper.m_ShortcutsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShortcutsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShortcutsActions @Shortcuts => new ShortcutsActions(this);

    // DashboardShortcuts
    private readonly InputActionMap m_DashboardShortcuts;
    private List<IDashboardShortcutsActions> m_DashboardShortcutsActionsCallbackInterfaces = new List<IDashboardShortcutsActions>();
    private readonly InputAction m_DashboardShortcuts_StartDuel;
    private readonly InputAction m_DashboardShortcuts_StartPvP;
    public struct DashboardShortcutsActions
    {
        private @BattlefieldHotkeys m_Wrapper;
        public DashboardShortcutsActions(@BattlefieldHotkeys wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartDuel => m_Wrapper.m_DashboardShortcuts_StartDuel;
        public InputAction @StartPvP => m_Wrapper.m_DashboardShortcuts_StartPvP;
        public InputActionMap Get() { return m_Wrapper.m_DashboardShortcuts; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DashboardShortcutsActions set) { return set.Get(); }
        public void AddCallbacks(IDashboardShortcutsActions instance)
        {
            if (instance == null || m_Wrapper.m_DashboardShortcutsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DashboardShortcutsActionsCallbackInterfaces.Add(instance);
            @StartDuel.started += instance.OnStartDuel;
            @StartDuel.performed += instance.OnStartDuel;
            @StartDuel.canceled += instance.OnStartDuel;
            @StartPvP.started += instance.OnStartPvP;
            @StartPvP.performed += instance.OnStartPvP;
            @StartPvP.canceled += instance.OnStartPvP;
        }

        private void UnregisterCallbacks(IDashboardShortcutsActions instance)
        {
            @StartDuel.started -= instance.OnStartDuel;
            @StartDuel.performed -= instance.OnStartDuel;
            @StartDuel.canceled -= instance.OnStartDuel;
            @StartPvP.started -= instance.OnStartPvP;
            @StartPvP.performed -= instance.OnStartPvP;
            @StartPvP.canceled -= instance.OnStartPvP;
        }

        public void RemoveCallbacks(IDashboardShortcutsActions instance)
        {
            if (m_Wrapper.m_DashboardShortcutsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDashboardShortcutsActions instance)
        {
            foreach (var item in m_Wrapper.m_DashboardShortcutsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DashboardShortcutsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DashboardShortcutsActions @DashboardShortcuts => new DashboardShortcutsActions(this);
    private int m_BattlefieldHotkeysSchemeIndex = -1;
    public InputControlScheme BattlefieldHotkeysScheme
    {
        get
        {
            if (m_BattlefieldHotkeysSchemeIndex == -1) m_BattlefieldHotkeysSchemeIndex = asset.FindControlSchemeIndex("BattlefieldHotkeys");
            return asset.controlSchemes[m_BattlefieldHotkeysSchemeIndex];
        }
    }
    private int m_DashboardShortcutsSchemeIndex = -1;
    public InputControlScheme DashboardShortcutsScheme
    {
        get
        {
            if (m_DashboardShortcutsSchemeIndex == -1) m_DashboardShortcutsSchemeIndex = asset.FindControlSchemeIndex("DashboardShortcuts");
            return asset.controlSchemes[m_DashboardShortcutsSchemeIndex];
        }
    }
    public interface IShortcutsActions
    {
        void OnPlayHandCards(InputAction.CallbackContext context);
        void OnRestartGame(InputAction.CallbackContext context);
        void OnSurrenderGame(InputAction.CallbackContext context);
    }
    public interface IDashboardShortcutsActions
    {
        void OnStartDuel(InputAction.CallbackContext context);
        void OnStartPvP(InputAction.CallbackContext context);
    }
}
